name: SuyuListening
description: 素语听力©️ is an app written by Flutter & Java for my lover 素素 to use to improve listening skill efficiently
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  #################
  #### 系统相关 ####
  #################
  # 使canvas能感知触摸
  touchable: ^0.2.0
  json_annotation: ^3.0.1
  device_info: ^1.0.0
  get: ^3.24.0
  # 加密
  crypto: ^2.1.5
  # 震动
  vibration: ^1.7.3
  # 检测键盘是否弹出
  keyboard_visibility: ^0.5.6
  
  ### 持久化
  path_provider: ^1.6.22
  shared_preferences: ^0.5.12+2
  sqflite: ^1.3.0  
  
  provider: ^4.3.2+2
  ### 屏幕适配
  flutter_screenutil: ^4.0.2+3
  ### 网络
  dio: ^3.0.8
  http: ^0.12.2
  flutter_downloader: ^1.5.2

  ### 音频
  audioplayers: ^0.17.3
  just_audio: ^0.6.9

  ### 动画增强
  simple_animations: ^1.3.3
  lottie: ^0.7.0+1

  ##############
  #### 组件 ####
  ##############
  # 下拉，上拉 刷新
  flutter_easyrefresh: 2.1.8
  # 听力的进度条滑块
  flutter_xlider: ^3.4.0
  # 头像
  circular_profile_avatar: ^1.0.6
  # 庆祝动画
  confetti: ^0.5.4+1
  # 自定义键盘上的功能区
  # keyboard_actions: ^3.3.1+1

  # 用在头像的自定义
  flutter_svg: ^0.19.1
  flutter_swiper: ^1.1.6
  modal_bottom_sheet: ^1.0.0+1
  # 评分
  flutter_simple_rating_bar: 0.0.3  
  # 用于显示下载的进度
  liquid_progress_indicator: ^0.3.2
  #
  circular_countdown_timer: ^0.0.9
  #
  badges: ^1.1.6
  #
  bordered_text: ^1.0.1
  # 给text打标签
  styled_text: ^1.0.3+3

  # onboarding页面
  introduction_screen: ^1.0.9

  #权限申请
  permission_handler: ^4.4.0
  # 超级强大的功能
  common_utils: ^1.2.1
  # 路由
  fluro: ^1.7.8
  # 正反面切换
  flip_card: ^0.4.4
  # 折线图
  flutter_sparkline: ^0.1.0
  implicitly_animated_reorderable_list: ^0.3.2
  # 垃圾
  search_page: ^1.4.0
  material_floating_search_bar: ^0.2.6
  # 日历
  flutter_calendar_carousel: ^1.5.2
  # 椭圆形状shape
  superellipse_shape: ^0.1.5
  # 侧边栏
  flutter_inner_drawer: "^0.5.7+2"
  #
  animated_text_kit: ^3.1.0
  # 聊天气泡
  flutter_chat_bubble: ^1.0.2
  # loading组件
  flutter_spinkit: "^4.1.2"
  ##############
  #### 弹窗 ####
  ##############
  material_dialogs: ^0.1.2
  flutter_beautiful_popup: ^1.5.0
  flutter_easyloading: ^2.0.0  
  cool_alert: ^1.0.3
  # 用在结束听力后的反馈
  emoji_feedback: ^0.1.0
     
  ###############
  #### icons ####
  ###############
  line_awesome_flutter: ^1.0.1
  cupertino_icons: ^0.1.2
  ionicons: ^0.0.3
  
  animated_theme_switcher: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0 #json数据生成实体类
  json2entity: 1.0.6
  json_serializable: ^3.3.0 #json数据生成实体类
flutter:  
  uses-material-design: true  
  assets:
    - assets/
    - assets/mic/      
    - assets/images/      
    - assets/images/popup/
    - assets/lotties/
    - assets/icons/
    - assets/icons/customAvatarIcons/
  fonts:
    - family: appIconFonts
      fonts:
        - asset: assets/icons/iconfont.ttf
    - family: logoFonts
      fonts:
        - asset: assets/fonts/logo.ttf              
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
